package spec

// Security Scheme Object
//
// Defines a security scheme that can be used by the operations.
//
// Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter, or as a
// query parameter), OAuth2's common flows (implicit, password, client credentials, and authorization code)
// as defined in RFC6749, and OpenID Connect Discovery.
//
// Please note that as of 2020, the implicit flow is about to be deprecated by OAuth 2.0 Security Best
// Current Practice. Recommended for most use cases is Authorization Code Grant flow with PKCE.
//
// See: https://spec.openapis.org/oas/v3.0.4.html#security-scheme-object
type SecurityScheme struct {
	// REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
	Type string `json:"type" yaml:"type"`
	// A description for security scheme. CommonMark syntax MAY be used for rich text representation.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// REQUIRED (apiKey). The name of the header, query or cookie parameter to be used.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
	// REQUIRED (apiKey). The location of the API key. Valid values are "query", "header", or "cookie".
	In string `json:"in,omitempty" yaml:"in,omitempty"`
	// REQUIRED (http). The name of the HTTP Authentication scheme to be used in the Authorization header
	// as defined in RFC7235 Section 5.1. The values used SHOULD be registered in the IANA Authentication
	// Scheme registry. The value is case-insensitive, as defined in RFC7235 Section 2.1.
	Scheme string `json:"scheme,omitempty" yaml:"scheme,omitempty"`
	// A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually
	// generated by an authorization server, so this information is primarily for documentation purposes.
	BearerFormat string `json:"bearerFormat,omitempty" yaml:"bearerFormat,omitempty"`
	// REQUIRED (oauth2). An object containing configuration information for the flow types supported.
	Flows *OAuthFlows `json:"flows,omitempty" yaml:"flows,omitempty"`
	// REQUIRED (openIdConnect). Well-known URL to discover the OpenID Connect Discovery provider metadata.
	OpenIdConnectUrl string `json:"openIdConnectUrl,omitempty" yaml:"openIdConnectUrl,omitempty"`
}
